permalink: /github/:year/:month/:day/:title.html
pygments: true
paginate: 5
paginate_files:
  - blog.html 
exclude:
  - gh-prx.sublime-project
  - gh-prx.sublime-workspace
  - start-thin.sh
  - auto-jekyll.sh
include:
  - github/
  - github/doc/
  - github/doc/r1-2-3/
  - github/doc/r1-2-3/index.html
