# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    exclude:
    - PxCoco/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'prx.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- task: DotNetCoreCLI@2
  displayName: Restore (Win)
  inputs:
    command: restore
    projects: '$(solution)'
    selectOrConfig: 'config'
    nugetConfigPath: NuGet.Config

- task: DotNetCoreCLI@2
  displayName: Build (Win)
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '"/p:Platform=$(BuildPlatform);Configuration=$(BuildConfiguration)" --no-restore'

- task: DotNetCoreCLI@2
  displayName: Unit Test (Win)
  inputs:
    command: test    
    projects: '**/*Tests.csproj'
    nobuild: true
    arguments: '"/p:Platform=$(BuildPlatform);Configuration=$(BuildConfiguration)" --no-restore'

- task: DotNetCoreCLI@2
  displayName: Pack (Win)
  inputs:
    command: pack
    searchPatternPack: 'Prexonite/Prexonite.csproj'
    nobuild: true
    configurationToPack: $(BuildConfiguration)
    buildProperties: Platform=$(BuildPlatform)

- task: PublishPipelineArtifact@0
  displayName: Publish to pipeline (Win)
  inputs:
    artifactName: 'binaries'
    targetPath: '$(Build.ArtifactStagingDirectory)'
