# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  tags:
    include:
    - 'pxcoco/v.*'

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  Version: '$(Build.BuildNumber)'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- powershell: |
    # Remove /refs/tags (10 chars) and pxcoco/v. (9 chars) from checkout string
    $ver = $env:BUILD_SOURCEBRANCH.remove(0, 19)
    Write-Host "##vso[task.setvariable variable=Version]$ver"
  displayName: 'Update version to Tag'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'PxCoco/PxCoco.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'PxCoco/PxCoco.sln'
    arguments: /p:Version=$(Version);Configuration=$(BuildConfiguration)

# There are no automated tests for PxCoco.

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: 'PxCoco/PxCoco.csproj'
    packagesToPack: 'PxCoco/PxCoco.csproj'
    nobuild: true
    configurationToPack: $(BuildConfiguration)
    buildProperties: Version=$(Version)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'binaries'
    targetPath: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: push
    publishVstsFeed: 'edge'
    allowPackageConflicts: false
