# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include:
    - PxCoco/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- displayName: "Install .NET Core"
  task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- displayName: "Restore NuGet packages"
  task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'PxCoco/PxCoco.sln'

- displayName: "Build"
  task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'PxCoco/PxCoco.sln'

# There are no automated tests for PxCoco.

- displayName: "Package"
  task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: 'PxCoco/PxCoco.csproj'
    configurationToPack: $(BuildConfiguration)
