# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include:
    - PxCoco/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- task: DotNetCoreCLI@2
  displayName: Restore (Win)
  inputs:
    command: restore
    projects: 'PxCoco/PxCoco.sln'

- task: DotNetCoreCLI@2
  displayName: Build (Win)
  inputs:
    command: build
    projects: 'PxCoco/PxCoco.sln'
    arguments: /p:Configuration=$(BuildConfiguration)

# There are no automated tests for PxCoco.

- task: DotNetCoreCLI@2
  displayName: Pack (Win)
  inputs:
    command: pack
    searchPatternPack: 'PxCoco/PxCoco.csproj'
    nobuild: true
    configurationToPack: '$(BuildConfiguration)'
